// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    FileReader: typeof import('./src/components/FileReader.vue')['default']
  }
}
