// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChartImage: typeof import('./src/components/ChartImage.vue')['default']
    ChartNode: typeof import('./src/components/ChartNode.vue')['default']
    ChartSvg: typeof import('./src/components/ChartSvg.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FileReader: typeof import('./src/components/FileReader.vue')['default']
    ReadPictureFile: typeof import('./src/components/ReadPictureFile.vue')['default']
    ReadPictureFIle: typeof import('./src/components/ReadPictureFIle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
